# Generated by Django 5.2.17 on 2026-10-08 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('nutrition_grade', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('unknown', 'unknown'), ('not-applicable', 'not-applicable')], db_index=True, default='unknown', max_length=14)),
                ('environmental_grade', models.CharField(choices=[('a-plus', 'a-plus'), ('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f'), ('unknown', 'unknown'), ('not-applicable', 'not-applicable')], default='unknown', max_length=14)),
                ('environmental_grade_estimated', models.CharField(blank=True, max_length=20)),
                ('nova_group', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('energy_kcal_100g', models.FloatField(blank=True, null=True)),
                ('proteins_100g', models.FloatField(blank=True, null=True)),
                ('fat_100g', models.FloatField(blank=True, null=True)),
                ('saturated_fat_100g', models.FloatField(blank=True, null=True)),
                ('carbohydrates_100g', models.FloatField(blank=True, null=True)),
                ('sugars_100g', models.FloatField(blank=True, null=True)),
                ('fiber_100g', models.FloatField(blank=True, null=True)),
                ('sodium_100g', models.FloatField(blank=True, null=True)),
                ('halal_labeled', models.BooleanField(default=False)),
                ('ingredients_text', models.TextField(blank=True)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('serving_size', models.CharField(blank=True, max_length=100)),
                ('categories_tags', models.JSONField(blank=True, default=list)),
                ('packaging_tags', models.JSONField(blank=True, default=list)),
                ('labels_tags', models.JSONField(blank=True, default=list)),
                ('ingredients_analysis_tags', models.JSONField(blank=True, default=list)),
                ('misc_tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('off', 'off'), ('manual', 'manual')], max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
